name: Master
on:
  push:
    branches:
      - master
  schedule:
    - cron: '0/10 * * * * ?'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: mkdir ./hello
    - name: Running
      run: |
        echo "Running!"
